# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4afc5f1209da3eecbd07ecfe9d499fa795ad7550908c97cb20ad0889aaf440ad4d24145f04134cc8c3f2d650e175bcf6978fd964b3d819dbed6ada00d2b6baa

test:
  secret_key_base: a45bbdb056958f4bee5fd352d629531b1ee8222eda8f54f744823bec06e927516ee0f3e68b2941b2d1dc908f6f4b85570c90b051df51cc4cfd965a5b7e558402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
